version: "3"
services:
  front-end:
    build: ./front-end
    ports:
      - "9000:9000"
    depends_on:
      - proxy

  back-end:
    build: ./back-end
    ports:
      - "5252:5252"

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end

